import type { Sprite } from "./pixel";

/** 10×10 pixel icons. Palette letters: see ICON_PAL in pixel.ts. */
export const ICONS = {
  // ---------- job props ----------
  chart: [
    "k.........",
    "k.......yy",
    "k.......yy",
    "k....cc.yy",
    "k....cc.yy",
    "k....cc.yy",
    "k.rr.cc.yy",
    "k.rr.cc.yy",
    "k.rr.cc.yy",
    "kkkkkkkkkk",
  ],
  phone: [
    "..kkkkkk..",
    "..kcccck..",
    "..kclcck..",
    "..kcllck..",
    "..kcclck..",
    "..kcccck..",
    "..kcccck..",
    "..kkkkkk..",
    "..kkwwkk..",
    "...kkkk...",
  ],
  antenna: [
    ".k......k.",
    "k..k..k..k",
    "k.k.yy.k.k",
    ".k..yy..k.",
    "....dd....",
    "....dd....",
    "....dd....",
    "...kddk...",
    "..kddddk..",
    ".kkkkkkkk.",
  ],
  robot: [
    "....y.....",
    "....k.....",
    ".kkkkkkkk.",
    ".kggggggk.",
    ".kgcggcgk.",
    ".kggggggk.",
    ".kgkkkkgk.",
    ".kkkkkkkk.",
    "..kg..gk..",
    "..kk..kk..",
  ],
  fish: [
    "..........",
    "...kkkk..k",
    "..kooookkk",
    ".kowoooook",
    ".koooooook",
    "..kooookkk",
    "...kkkk..k",
    "..........",
    "..........",
    "..........",
  ],
  binoculars: [
    "..........",
    ".kkk..kkk.",
    ".kdk..kdk.",
    "kddkkkkddk",
    "kddk..kddk",
    "kcck..kcck",
    "kcck..kcck",
    ".kk....kk.",
    "..........",
    "..........",
  ],
  bin: [
    "...kkkk...",
    ".kkkkkkkk.",
    "..kllllk..",
    "..klwwlk..",
    "..kwllwk..",
    "..klwwlk..",
    "..kllllk..",
    "..kllllk..",
    "..kllllk..",
    "...kkkk...",
  ],
  magnifier: [
    "..kkkk....",
    ".kwccck...",
    "kcccccck..",
    "kcccccck..",
    ".kcccck...",
    "..kkkk....",
    "......mm..",
    ".......mm.",
    "........mm",
    "..........",
  ],
  pencil: [
    "........kk",
    ".......kik",
    "......kyk.",
    ".....kyk..",
    "....kyk...",
    "...kyk....",
    "..kyk.....",
    ".ksk......",
    ".kk.......",
    "k.........",
  ],
  scissors: [
    "k.......k.",
    ".k.....k..",
    "..k...k...",
    "...k.k....",
    "....k.....",
    "...k.k....",
    ".rr...rr..",
    "r..r.r..r.",
    "r..r.r..r.",
    ".rr...rr..",
  ],
  house: [
    "....kk....",
    "...krrk...",
    "..krrrrk..",
    ".krrrrrrk.",
    "krrrrrrrrk",
    ".kssssssk.",
    ".kcssmmsk.",
    ".ksssmmsk.",
    ".ksssmmsk.",
    ".kkkkkkkk.",
  ],
  tree: [
    "...kkkk...",
    "..kllllk..",
    ".kllplllk.",
    "kllllpllk.",
    "kplllllpk.",
    ".kllllllk.",
    "..kkmmkk..",
    "....mm....",
    "....mm....",
    "..kkkkkk..",
  ],
  turbine: [
    ".....w....",
    ".....w....",
    ".....w....",
    "....kkk...",
    "...w.g.w..",
    "..w..g..w.",
    ".....g....",
    ".....g....",
    ".....g....",
    "cccccccccc",
  ],
  solar: [
    "yy........",
    "yy........",
    ".kkkkkkkk.",
    ".kwbbkwbk.",
    ".kbbbkbbk.",
    ".kkkkkkkk.",
    ".kwbbkwbk.",
    ".kbbbkbbk.",
    ".kkkkkkkk.",
    "....dd....",
  ],
  anchor: [
    "....kk....",
    "...k..k...",
    "....kk....",
    "..kkkkkk..",
    "....kk....",
    "....kk....",
    "k...kk...k",
    "kk..kk..kk",
    ".kk.kk.kk.",
    "..kkkkkk..",
  ],
  bike: [
    "..........",
    "......kk..",
    "..kk...k..",
    "...rrrrr..",
    "..r..r.r..",
    ".kk....kk.",
    "k..k..k..k",
    "k..k..k..k",
    ".kk....kk.",
    "..........",
  ],
  carrot: [
    ".....l.l..",
    "......ll..",
    ".....kkk..",
    "....kook..",
    "....kook..",
    "...koook..",
    "...kook...",
    "..kook....",
    "..kok.....",
    "..kk......",
  ],
  drop: [
    "....kk....",
    "...kcck...",
    "...kcck...",
    "..kccwck..",
    ".kccccwck.",
    ".kcccccck.",
    ".kcccccck.",
    "..kcccck..",
    "...kkkk...",
    "..........",
  ],
  pot: [
    "..w..w....",
    "...w..w...",
    "..........",
    "kkkkkkkkkk",
    ".krrrrrrk.",
    "kkrrrrrrkk",
    ".krrrrrrk.",
    ".krrrrrrk.",
    "..kkkkkk..",
    "..........",
  ],
  bee: [
    "..........",
    "...ww.ww..",
    "...wwkww..",
    "..kkkkkkk.",
    ".kyykyykyk",
    ".kyykyykyk",
    "..kkkkkkk.",
    "..........",
    "..........",
    "..........",
  ],
  mic: [
    "...kkkk...",
    "..kddddk..",
    "..kdgdgk..",
    "..kddddk..",
    "...kkkk...",
    "....kk....",
    "....kk....",
    "....kk....",
    "...kkkk...",
    "..........",
  ],
  mask: [
    ".kkkkkkk..",
    "kwwwwwwwk.",
    "kwkwwwkwk.",
    "kwwwwwwwk.",
    "kwkwwwkwk.",
    ".kwkkkwk..",
    "..kwwwk...",
    "...kkk....",
    "..........",
    "..........",
  ],
  newspaper: [
    "kkkkkkkkk.",
    "kwwwwwwwk.",
    "kwkkkkkwk.",
    "kwwwwwwwk.",
    "kwkkwgggk.",
    "kwkkwwwwk.",
    "kwwwwgggk.",
    "kwgggwwwk.",
    "kkkkkkkkk.",
    "..........",
  ],
  brush: [
    "........kk",
    ".......kmk",
    "......kmk.",
    ".....kmk..",
    "....kmk...",
    "...kgk....",
    "..kiik....",
    ".kiiik....",
    ".kiik.....",
    "..kk......",
  ],

  // ---------- UI ----------
  speaker: [
    ".....k....",
    "....kk..k.",
    "kkkkwk...k",
    "kwwwwk.k.k",
    "kwwwwk.k.k",
    "kwwwwk.k.k",
    "kkkkwk...k",
    "....kk..k.",
    ".....k....",
    "..........",
  ],
  book: [
    ".kkkkkkkk.",
    ".kmmmmmmk.",
    ".kmyyyymk.",
    ".kmmmmmmk.",
    ".kmmmmmmk.",
    ".kmmyymmk.",
    ".kmmmmmmk.",
    ".kmmmmmmk.",
    ".kwwwwwwk.",
    ".kkkkkkkk.",
  ],
  check: [
    "..........",
    "..........",
    "........kk",
    ".......kk.",
    "k.....kk..",
    "kk...kk...",
    ".kk.kk....",
    "..kkk.....",
    "...k......",
    "..........",
  ],
  star: [
    "....kk....",
    "....kk....",
    "...kyyk...",
    "kkkkyykkkk",
    ".kyyyyyyk.",
    "..kyyyyk..",
    "..kyyyyk..",
    ".kyykkyyk.",
    ".kkk..kkk.",
    "..........",
  ],
  plus: [
    "..........",
    "....kk....",
    "....kk....",
    "....kk....",
    ".kkkkkkkk.",
    ".kkkkkkkk.",
    "....kk....",
    "....kk....",
    "....kk....",
    "..........",
  ],
  minus: [
    "..........",
    "..........",
    "..........",
    "..........",
    ".kkkkkkkk.",
    ".kkkkkkkk.",
    "..........",
    "..........",
    "..........",
    "..........",
  ],
  map: [
    "kkkkkkkkkk",
    "kccssllcck",
    "kcsslllcck",
    "kcsllrllck",
    "kccsllllck",
    "kccslllcck",
    "kcccsslcck",
    "kccccsscck",
    "kcccccccck",
    "kkkkkkkkkk",
  ],
  arrow: [
    "..........",
    "...k......",
    "..kk......",
    ".kkkkkkkk.",
    "kkkkkkkkk.",
    ".kkkkkkkk.",
    "..kk......",
    "...k......",
    "..........",
    "..........",
  ],
  globe: [
    "..kkkkkk..",
    ".kcllccck.",
    "kcllllccck",
    "kcclllccck",
    "kccclcclck",
    "kcccccllck",
    "kcccccllck",
    ".kcccclck.",
    "..kkkkkk..",
    "..........",
  ],
  bag: [
    "...kkkk...",
    "..k....k..",
    ".kkkkkkkk.",
    ".krrrrrrk.",
    ".krkkkkrk.",
    ".krkyykrk.",
    ".krkkkkrk.",
    ".krrrrrrk.",
    ".krrrrrrk.",
    ".kkkkkkkk.",
  ],
  hammer: [
    "kkkkk.....",
    "kdddk.....",
    "kddddk....",
    "kkkdmk....",
    "...kmmk...",
    "....kmmk..",
    ".....kmmk.",
    "......kmmk",
    ".......kk.",
    "..........",
  ],
  question: [
    "..kkkkk...",
    ".kk...kk..",
    ".......kk.",
    "......kk..",
    ".....kk...",
    "....kk....",
    "....kk....",
    "..........",
    "....kk....",
    "....kk....",
  ],
  expand: [
    "kkk....kkk",
    "kk......kk",
    "k.k....k.k",
    "..........",
    "..........",
    "..........",
    "..........",
    "k.k....k.k",
    "kk......kk",
    "kkk....kkk",
  ],
  scroll: [
    ".kkkkkkkk.",
    "kssssssssk",
    ".kwwwwwwk.",
    ".kwkkkkwk.",
    ".kwwwwwwk.",
    ".kwkkkwwk.",
    ".kwwwwwwk.",
    ".kwkkkkwk.",
    "kssssssssk",
    ".kkkkkkkk.",
  ],
} satisfies Record<string, string[]>;

export type IconName = keyof typeof ICONS;

export const icon = (name: IconName): Sprite => ({ rows: ICONS[name] });

/** Each job's signature prop. */
export const JOB_PROP: Record<string, IconName> = {
  "data-scientist-climat": "chart",
  "developpeuse-appli-sobre": "phone",
  "ingenieure-capteurs": "antenna",
  "roboticienne-marine": "robot",
  "biologiste-marine": "fish",
  "garde-parc-national": "binoculars",
  "responsable-tri-recyclage": "bin",
  "animatrice-nature": "magnifier",
  "ecoconceptrice-objets": "pencil",
  "styliste-mode-durable": "scissors",
  "architecte-bioclimatique": "house",
  "paysagiste-urbaine": "tree",
  "ingenieure-eolien-mer": "turbine",
  "installatrice-solaire": "solar",
  "ingenieure-bateaux-propres": "anchor",
  "urbaniste-mobilite": "bike",
  "maraichere-bio": "carrot",
  hydrologue: "drop",
  "cheffe-anti-gaspi": "pot",
  apicultrice: "bee",
  "organisatrice-evenements-verts": "mic",
  "decoratrice-spectacles-recup": "mask",
  "journaliste-environnement": "newspaper",
  "illustratrice-planete": "brush",
};

export const propOf = (jobId: string): IconName => JOB_PROP[jobId] ?? "star";

/** Terra the seagull guide, 16×16. */
export const TERRA: Sprite = {
  rows: [
    "................",
    "......kkkk......",
    ".....kyyyyk.....",
    "....kyyyyyykkk..",
    "....kwwwwwwk....",
    "...kwwkwwwwwk...",
    "..kowwwwwwwwk...",
    ".kooowwwwwwwk...",
    "..kkwwwwwwwwk...",
    "...kwwwwwwwwwk..",
    "..kwwwwwggggwk..",
    "..kwwwwggggggk..",
    "...kwwwwgggkk...",
    "....kkkkkkk.....",
    ".....oo..oo.....",
    "................",
  ],
};
